name: amf3-radar-examples-dev
channels:
  - conda-forge
  - defaults
  - pyviz
dependencies:
  - python=3.9
  - matplotlib
  - jupyterlab
  - cartopy
  - numpy
  - dask
  - distributed
  - xarray
  - pandas
  - fiona
  - pip
  - pip:
    - -r doc-requirements.txt
    - arm_pyart
